# Generated by Django 4.2.7 on 2025-07-18 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("CARDIOLOGY", "Cardiology"),
                            ("DERMATOLOGY", "Dermatology"),
                            ("ENDOCRINOLOGY", "Endocrinology"),
                            ("GASTROENTEROLOGY", "Gastroenterology"),
                            ("NEUROLOGY", "Neurology"),
                            ("ONCOLOGY", "Oncology"),
                            ("ORTHOPEDICS", "Orthopedics"),
                            ("PEDIATRICS", "Pediatrics"),
                            ("PSYCHIATRY", "Psychiatry"),
                            ("UROLOGY", "Urology"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("years_of_experience", models.PositiveIntegerField()),
                ("bio", models.TextField(blank=True, null=True)),
                ("availability", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
